const express = require('express')
const path = require('path')
var cookieParser = require("cookie-parser")
var session = require("express-session")
const app = express()
const UserController = require('./controllers/user')
const { UserModel } = require('./models')
var debug = require("debug")("index.js");

app.use(express.json())
app.use(express.urlencoded(({ extended: false })))
app.set('view engine', 'ejs')
app.set('views', path.join(__dirname, 'views'))


app.use('/public', express.static(path.join(__dirname, 'public')))
app.use('/users', UserController)
app.use(cookieParser())
app.use(
  session({
    secret: "demoapp",
    name: "app",
    resave: true,
    saveUninitialized: true,
    cookie: { maxAge: 5000 } /* 6000 ms? 6 seconds -> wut? :S */
  })
);
const checkLoggedIn = function (request, response, next) {
  if (request.session.loggedIn) {
    // debug(
    //   "checkLoggedIn(), req.session.loggedIn:",
    //   req.session.loggedIn,
    //   "executing next()"
    // );
    next();
  } else {
    // debug(
    //   "checkLoggedIn(), req.session.loggedIn:",
    //   req.session.loggedIn,
    //   "rendering login"
    // );
    response.redirect("login");
  }
}


app.get('/', checkLoggedIn, async function (request, response) {
  // res.sendFile(path.join(__dirname,'index.html'))
  const allUsers = await UserModel.getAllUsers()

  console.log(allUsers)
  response.render('index', { data: allUsers || [] })
})

app.post('/login', async function (req, res) {
  const { username, password } = req.body
  try {
    const user = await UserModel.findUserByUsername(username)
    // FAIL-FAST 
    console.log({ user });
    if (user && (user.username === username) && (user.password === password)) {
      req.session.loggedIn = true
      res.redirect('/')

    } else {
      throw new Error('Unauthorized access')
      // if(!user || user.username !== username || user.password !== password) throw new Error('Unauthorized access')
      // req.session.loggedIn = true
    }
  }
  catch (error) {
    console.error(error)
    res.render('login', { errorMessage: error.message })
  }
})

app.get('/login', function (req, res) {
  if (req.session.loggedIn) res.redirect('/')
  res.render('login')
})

app.get('/register', function (req, res) {
  if (req.session.loggedIn) res.redirect('/')
  res.render('register')
})

app.post('/register', async function (req, res) {
  const { username, password, confirmPassword } = req.body

  // Server-side Validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const passwordRegex = /^(?=.*[0-9])(?=.*[!@#$%^&*()_+\-=[\]{};':"\\|,.<>\/?]).{6,}$/;

  try {
    if (!username || !emailRegex.test(username)) {
      throw new Error('Invalid username format (must be email)')
    }
    if (!password || !passwordRegex.test(password)) {
      throw new Error('Password must be at least 6 characters, contain at least 1 number and 1 special character')
    }
    if (password !== confirmPassword) {
      throw new Error('Passwords do not match')
    }

    // Check if user already exists
    const existingUser = await UserModel.findUserByUsername(username)
    if (existingUser) {
      throw new Error('User already exists')
    }

    // Create new user
    const newUser = {
      username,
      password
      // id will be generated by model
    }

    await UserModel.insertUser(newUser)
    res.redirect('/login')

  } catch (error) {
    console.error(error)
    res.render('register', { errorMessage: error.message })
  }
})

app.post('/api/register', async function (req, res) {
  const { username, password } = req.body

  // Note: confirmPassword check is done on client side, but could double check here if sent
  // Server-side Validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const passwordRegex = /^(?=.*[0-9])(?=.*[!@#$%^&*()_+\-=[\]{};':"\\|,.<>\/?]).{6,}$/;

  try {
    if (!username || !emailRegex.test(username)) {
      throw new Error('Invalid username format (must be email)')
    }
    if (!password || !passwordRegex.test(password)) {
      throw new Error('Password must be at least 6 characters, contain at least 1 number and 1 special character')
    }

    // Check if user already exists
    const existingUser = await UserModel.findUserByUsername(username)
    if (existingUser) {
      throw new Error('User already exists')
    }

    // Create new user
    const newUser = {
      username,
      password
    }

    await UserModel.insertUser(newUser)
    res.json({ status: true, message: 'Registration successful' })

  } catch (error) {
    console.error(error)
    res.status(400).json({ status: false, message: error.message })
  }
})



app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})